// @ts-nocheck -- skip type checking
import * as meta_2 from "../content/docs/core-concepts/meta.json?collection=meta&hash=1763556927781"
import * as meta_1 from "../content/docs/getting-started/meta.json?collection=meta&hash=1763556927781"
import * as meta_0 from "../content/docs/meta.json?collection=meta&hash=1763556927781"
import * as docs_7 from "../content/docs/getting-started/quick-start.mdx?collection=docs&hash=1763556927781"
import * as docs_6 from "../content/docs/getting-started/installation.mdx?collection=docs&hash=1763556927781"
import * as docs_5 from "../content/docs/getting-started/configuration.mdx?collection=docs&hash=1763556927781"
import * as docs_4 from "../content/docs/core-concepts/signals.mdx?collection=docs&hash=1763556927781"
import * as docs_3 from "../content/docs/core-concepts/measures.mdx?collection=docs&hash=1763556927781"
import * as docs_2 from "../content/docs/core-concepts/index.mdx?collection=docs&hash=1763556927781"
import * as docs_1 from "../content/docs/core-concepts/entities.mdx?collection=docs&hash=1763556927781"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1763556927781"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.doc<typeof _source.docs>([{ info: {"path":"index.mdx","absolutePath":"/Users/ajaxdavis/repos/blocks/apps/docs/content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"core-concepts/entities.mdx","absolutePath":"/Users/ajaxdavis/repos/blocks/apps/docs/content/docs/core-concepts/entities.mdx"}, data: docs_1 }, { info: {"path":"core-concepts/index.mdx","absolutePath":"/Users/ajaxdavis/repos/blocks/apps/docs/content/docs/core-concepts/index.mdx"}, data: docs_2 }, { info: {"path":"core-concepts/measures.mdx","absolutePath":"/Users/ajaxdavis/repos/blocks/apps/docs/content/docs/core-concepts/measures.mdx"}, data: docs_3 }, { info: {"path":"core-concepts/signals.mdx","absolutePath":"/Users/ajaxdavis/repos/blocks/apps/docs/content/docs/core-concepts/signals.mdx"}, data: docs_4 }, { info: {"path":"getting-started/configuration.mdx","absolutePath":"/Users/ajaxdavis/repos/blocks/apps/docs/content/docs/getting-started/configuration.mdx"}, data: docs_5 }, { info: {"path":"getting-started/installation.mdx","absolutePath":"/Users/ajaxdavis/repos/blocks/apps/docs/content/docs/getting-started/installation.mdx"}, data: docs_6 }, { info: {"path":"getting-started/quick-start.mdx","absolutePath":"/Users/ajaxdavis/repos/blocks/apps/docs/content/docs/getting-started/quick-start.mdx"}, data: docs_7 }]);
export const meta = _runtime.meta<typeof _source.meta>([{ info: {"path":"meta.json","absolutePath":"/Users/ajaxdavis/repos/blocks/apps/docs/content/docs/meta.json"}, data: meta_0 }, { info: {"path":"getting-started/meta.json","absolutePath":"/Users/ajaxdavis/repos/blocks/apps/docs/content/docs/getting-started/meta.json"}, data: meta_1 }, { info: {"path":"core-concepts/meta.json","absolutePath":"/Users/ajaxdavis/repos/blocks/apps/docs/content/docs/core-concepts/meta.json"}, data: meta_2 }]);