# Blocks Configuration: Blog Content Validator
# Domain: Content quality validation for markdown blog posts

project:
  name: "Blog Content Validator"
  domain: "content.blog.validation"

# Philosophy statements guide AI validation
philosophy:
  - "Blog posts must include humor and maintain an engaging, conversational tone"
  - "Content should be accessible and relatable, not overly formal or academic"

# Domain semantics
domain:
  entities:
    blog_post:
      description: "A blog post in markdown format"
      fields:
        - path
        - content

    validation_result:
      description: "Result of content validation"
      fields:
        - valid
        - message

  signals:
    humor_presence:
      description: "Detects presence and quality of humor in content"
      extraction_hint: "Look for wit, personal anecdotes, conversational tone, storytelling"

    conversational_tone:
      description: "Measures how conversational and engaging the writing is"
      extraction_hint: "Check for second-person pronouns (you, your), first-person (I, we), questions, casual language"

  measures:
    humor_score:
      constraints:
        - "Must include humor or light-hearted elements"
        - "Humor should be authentic, not forced"

    tone_quality:
      constraints:
        - "Must be conversational and engaging"
        - "Avoid corporate jargon and overly formal language"

# Block definitions
blocks:
  # Default domain rules for all blog validators
  domain_rules:
    - id: humor_required
      description: "Blog posts must include humor, wit, or light-hearted commentary"
    - id: conversational_tone
      description: "Writing must be conversational, using 'you' and 'I' to connect with readers"
    - id: no_corporate_speak
      description: "Avoid corporate jargon like 'leverage', 'synergy', 'paradigm shift'"

  validator.blog_post:
    type: validator
    description: "Validates blog post content for humor and conversational tone"
    path: "validators/blog-post"
    inputs:
      - name: post
        type: entity.blog_post
        description: "Blog post to validate"
    outputs:
      - name: result
        type: entity.validation_result
        measures: [humor_score, tone_quality]
        constraints:
          - "Must detect engaging, conversational content"
          - "Must ensure humor is present"
    # Inherits blocks.domain_rules automatically

# Validator configuration
validators:
  schema:
    - id: io_schema
      run: "schema.io"

  shape:
    - id: export_shape
      run: "shape.exports"

  domain:
    - id: domain_alignment
      run: "domain.validation"

# Validation pipeline
pipeline:
  name: "blog_content_validation"
  steps:
    - id: schema
      run: "schema.io"
    - id: shape
      run: "shape.exports"
    - id: domain
      run: "domain.validation"

# Discovery configuration
targets:
  kind: "block"
  discover:
    root: "validators"

# Agent configuration
agent:
  mode: "content_validator"
  rules:
    - "Always read blocks.yml before creating or modifying validators"
    - "Always run blocks CLI after validator changes"
    - "Domain validator checks for humor and tone in markdown source"
  cli:
    single: "blocks run {name}"
    all: "blocks run --all"
